[workspace]
members = [
  "associated-token-account/program",
  "examples/rust/cross-program-invocation",
  "examples/rust/custom-heap",
  "examples/rust/logging",
  "examples/rust/sysvar",
  "examples/rust/transfer-lamports",
  "feature-proposal/program",
  "feature-proposal/cli",
  "memo/program",
  "shared-memory/program",
  "stake-pool/cli",
  "stake-pool/program",
  "themis/program_ristretto",
  "token-lending/program",
  "token-swap/program",
  "token/cli",
  "token/perf-monitor",
  "token/program",
  "token/program-v3",
  "utils/cgen",
  "utils/test-client",
]
exclude = [
  "themis/client_ristretto",
]
