[workspace]
members = [
  "associated-token-account/program",
  "binary-option/program",
  "binary-oracle-pair/program",
  "examples/rust/cross-program-invocation",
  "examples/rust/custom-heap",
  "examples/rust/logging",
  "examples/rust/sysvar",
  "examples/rust/transfer-lamports",
  "farms/farm-client",
  "farms/farm-ctrl",
  "farms/farm-rpc",
  "farms/farm-sdk",
  "farms/router-main",
  "farms/router-raydium",
  "farms/router-saber",
  "farms/router-orca",
  "farms/vaults",
  "feature-proposal/program",
  "feature-proposal/cli",
  "governance/voter-weight-addin/program",
  "governance/program",
  "governance/test-sdk",
  "governance/tools",
  "governance/chat/program",
  "libraries/math",
  "memo/program",
  "name-service/program",
  "record/program",
  "shared-memory/program",
  "stake-pool/cli",
  "stake-pool/program",
  "stateless-asks/program",
  "token-lending/cli",
  "token-lending/program",
  "token-swap/program",
  "token-swap/program/fuzz",
  "token/cli",
  "token/program",
  "token/program-2022",
  "utils/cgen",
  "utils/test-client",
  "token-lending/flash_loan_receiver",
]
exclude = [
  "themis/client_ristretto",
  "themis/program_ristretto",
]

[profile.dev]
split-debuginfo = "unpacked"
