[package]
name = "spl-associated-token-account"
version = "1.0.0"
description = "Solana Program Library Associated Token Account"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/solana-labs/solana-program-library"
license = "Apache-2.0"
edition = "2018"

[features]
no-entrypoint = []

[dependencies]
solana-program = "1.4.4"
spl-token = { version = "3.0", path = "../../token/program", features = ["no-entrypoint"] }

[dev-dependencies]
solana-program-test = "1.4.4"
solana-sdk = "1.4.4"
tokio = { version = "0.3", features = ["macros"]}

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[workspace]
