
# Note: This crate must be built using do.sh

[package]
name = "spl-token-tests"
version = "0.1.0"
description = "System tests and benches for spl-token"
authors = ["Solana Maintainers <maintainers@solana.com>"]
repository = "https://github.com/solana-labs/solana-program-library"
license = "Apache-2.0"
edition = "2018"

[dependencies]
byteorder = "1.3.2"
num-derive = "0.2"
num-traits = "0.2"
spl-token = { path = "../program" }
solana-sdk = { version = "=1.0.9", default-features = false, features=["program"] }
solana-sdk-bpf-test = { path = "../../node_modules/@solana/web3.js/bpf-sdk/rust/test", default-features = false }
solana-bpf-loader-program = { version = "=1.0.9" }
solana-logger = { version = "=1.0.9" }

