[package]
name = "spl-token-2022"
version = "0.2.0"
description = "Solana Program Library Token 2022"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/solana-labs/solana-program-library"
license = "Apache-2.0"
edition = "2018"
exclude = ["js/**"]

[features]
no-entrypoint = []
test-bpf = []

[dependencies]
arrayref = "0.3.6"
bytemuck = { version = "1.7.2", features = ["derive"] }
num-derive = "0.3"
num-traits = "0.2"
num_enum = "0.5.4"
solana-program = "1.9.9"
solana-zk-token-sdk = "0.8.1"
spl-memo = { version = "3.0.1", path = "../../memo/program", features = [ "no-entrypoint" ] }
spl-token = { version = "3.3",  path = "../program", features = ["no-entrypoint"] }
thiserror = "1.0"

[dev-dependencies]
lazy_static = "1.4.0"
serial_test = "0.5.1"
solana-program-test = "1.9.9"
solana-sdk = "1.9.9"

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
