[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
description = "SPL-Stake-Pool Command-line Utility"
edition = "2018"
homepage = "https://spl.solana.com/stake-pool"
license = "Apache-2.0"
name = "spl-stake-pool-cli"
repository = "https://github.com/solana-labs/solana-program-library"
version = "2.0.1"

[dependencies]
clap = "2.33.3"
serde_json = "1.0.57"
solana-account-decoder = { version = "1.3.9" }
solana-clap-utils = { version = "1.3.9"}
solana-cli-config = { version = "1.3.9" }
solana-client = { version = "1.3.9" }
solana-logger = { version = "1.3.9" }
solana-sdk = { version = "1.3.9" }
spl-stake-pool = { version = "2.0", path="../program" }

[[bin]]
name = "spl-stake-pool"
path = "src/main.rs"
