[package]
name = "spl-governance"
version = "2.1.4"
description = "Solana Program Library Governance Program"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/solana-labs/solana-program-library"
license = "Apache-2.0"
edition = "2018"

[features]
no-entrypoint = []
test-bpf = []

[dependencies]
arrayref = "0.3.6"
bincode = "1.3.2"
borsh = "0.9.1"
num-derive = "0.3"
num-traits = "0.2"
serde = "1.0.130"
serde_derive = "1.0.103"
solana-program = "1.9.2"
spl-token = { version = "3.2", path = "../../token/program", features = [ "no-entrypoint" ] }
spl-governance-tools= { version = "0.1.0", path ="../tools"}
thiserror = "1.0"

[dev-dependencies]
assert_matches = "1.5.0"
base64 = "0.13"
lazy_static = "1.4.0"
proptest = "1.0"
solana-program-test = "1.9.2"
solana-sdk = "1.9.2"
spl-governance-test-sdk = { version = "0.1.0", path ="../test-sdk"}


[lib]
crate-type = ["cdylib", "lib"]
