name: Token Pull Request

on:
  pull_request:
    paths:
    - 'associated-token-account/**'
    - 'token/**'
  push:
    branches: [master]
    paths:
    - 'associated-token-account/**'
    - 'token/**'

jobs:
  cargo-test-bpf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set env vars
        run: |
          source ci/rust-version.sh
          echo "RUST_STABLE=$rust_stable" >> $GITHUB_ENV
          source ci/solana-version.sh
          echo "SOLANA_VERSION=$solana_version" >> $GITHUB_ENV

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_STABLE }}
          override: true
          profile: minimal

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: cargo-build-${{ hashFiles('**/Cargo.lock') }}-${{ env.RUST_STABLE}}

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/rustfilt
          key: cargo-bpf-bins-${{ runner.os }}

      - uses: actions/cache@v2
        with:
          path: ~/.cache/solana
          key: solana-${{ env.SOLANA_VERSION }}

      - name: Install dependencies
        run: |
          ./ci/install-build-deps.sh
          ./ci/install-program-deps.sh
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH

      - name: Build and test
        run: ./ci/cargo-test-bpf.sh token

      - name: Build and test
        run: ./ci/cargo-test-bpf.sh associated-token-account

      - name: Upload programs
        uses: actions/upload-artifact@v2
        with:
          name: token-programs
          path: "target/deploy/*.so"
          if-no-files-found: error

  js-test:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 14.x
    needs: cargo-test-bpf
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - uses: actions/cache@v2
        with:
          path: ~/.cache/yarn
          key: node-${{ hashFiles('token/js/yarn.lock') }}
          restore-keys: |
            node-
      - name: Download programs
        uses: actions/download-artifact@v2
        with:
          name: token-programs
          path: target/deploy
      - run: ./ci/js-test-token.sh
